name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write  # Required for OIDC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock

      - name: Set up Python 3.11
        run: uv python install 3.11

      - name: Install SWI-Prolog
        run: |
          sudo apt-get update
          sudo apt-get install -y swi-prolog-nox

      - name: Install dependencies
        run: |
          uv sync --all-extras

      - name: Show environment
        run: |
          uv run python -V
          uv pip list
          swipl --version

      - name: Run tests
        env:
          PYTHONHASHSEED: "0"          # make runs more deterministic
          PROLOG_STRESS_SCALE: "0.1"   # reduce stress test scale for CI
        run: |
          uv run pytest -q --maxfail=5 --disable-warnings -ra \
            --cov=prolog --cov-branch --cov-report=xml \
            --cov-report=term-missing:skip-covered \
            --junitxml=pytest.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: pytest.xml
          if-no-files-found: ignore

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.xml
            .coverage
          if-no-files-found: ignore

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          files: ./coverage.xml
          fail_ci_if_error: false
          verbose: true