name: Docs Site (MkDocs)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'mkdocs/**'
      - 'docs/**'
      - '.github/workflows/docs-site.yml'
  pull_request:
    paths:
      - 'mkdocs/**'
      - 'docs/**'
      - '.github/workflows/docs-site.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    name: Build MkDocs site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Sync dependencies (docs extra)
        run: uv sync --extra docs

      - name: Build MkDocs
        run: uv run --extra docs mkdocs build -f mkdocs/mkdocs.yml

      - name: Upload Pages artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v3
        with:
          path: mkdocs/site

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
