site_name: PyLog User Guide
site_description: User documentation for the PyLog Prolog interpreter with CLP(FD)
site_dir: site
repo_url: https://github.com/xpqz/pylog
repo_name: xpqz/pylog
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
    - toc.integrate
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.critic
extra:
  generator: false
nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/install.md
      - REPL: getting-started/repl.md
      - Hello Prolog: getting-started/hello-prolog.md
      - JSON Quickstart: getting-started/json-quickstart.md
  - Prolog Basics:
      - Terms: basics/terms.md
      - Facts and Rules: basics/facts-and-rules.md
      - Queries and Unification: basics/queries-and-unification.md
      - Lists and Structures: basics/lists-and-structures.md
      - Dicts: basics/dicts.md
      - Control: basics/control.md
      - Arithmetic: basics/arithmetic.md
      - Operators: basics/operators.md
      - Core Built-ins: basics/builtins.md
  - CLP(FD):
      - Introduction: clpfd/intro.md
      - Domains and in/2: clpfd/domains-and-in.md
      - Linear Constraints: clpfd/linear-constraints.md
      - Reification: clpfd/reification.md
      - Sum Constraints: clpfd/sum-constraints.md
      - all_different/1: clpfd/all-different.md
      - Labelling: clpfd/labeling.md
      - Examples: clpfd/examples.md
  - Cookbook:
      - List processing: cookbook/list-processing.md
      - List utilities: cookbook/list-utilities.md
      - Flatten: cookbook/flatten.md
      - Sorting (quicksort): cookbook/sorting-quicksort.md
      - Sorting (mergesort): cookbook/mergesort.md
      - Permutations: cookbook/permutations.md
      - Family relations: cookbook/family-relations.md
      - Graph reachability: cookbook/graph-reachability.md
      - Path with visited: cookbook/path-with-visited.md
      - Difference lists: cookbook/difference-lists.md
      - Towers of Hanoi: cookbook/hanoi.md
      - Binary trees: cookbook/binary-trees.md
      - Primes: cookbook/primes.md
      - Peano arithmetic: cookbook/peano-arithmetic.md
      - Map coloring: cookbook/map-coloring.md
      - Subset sum: cookbook/subset-sum.md
      - SEND+MORE=MONEY: cookbook/send-more-money.md
      - Sudoku row: cookbook/sudoku-row.md
      - Sudoku (9x9): cookbook/sudoku.md
      - N‑queens: cookbook/n-queens.md
      - Scheduling: cookbook/scheduling.md
      - JSON recipes: cookbook/json-recipes.md
  - Reference:
      - Built-ins: reference/builtins-reference.md
      - JSON: reference/json.md
      - REPL commands: reference/repl-commands.md
      - Runtime database: reference/runtime-db.md
      - CLI: reference/cli.md
      - Operators table: reference/operators-table.md
      - Operators cheat sheet: reference/operators-cheatsheet.md
      - Grammar summary: reference/grammar-summary.md
      - Trace format: reference/trace-format.md
      - Errors: reference/errors.md
  - Guides:
      - REPL tips & shortcuts: guides/repl-tips.md
      - Tracing and debugging: guides/tracing-and-debugging.md
      - Embedding JSON I/O: guides/embedding-json-io.md
      - Fast CLP(FD) in REPL: guides/fast-clpfd-repl.md
      - Control gotchas: guides/control-gotchas.md
      - Performance and limits: guides/performance-and-limits.md
      - ISO compatibility: guides/compatibility-iso.md
  - FAQ: faq.md
